site_name: iLLeniumStudios
site_url: https://docs.illenium.dev
theme:
  logo: assets/logo.png
  favicon: assets/favicon.png
  name: material
  palette:
  - scheme: default
    media: "(prefers-color-scheme: light)"
    toggle:
      icon: material/brightness-7
      name: Switch to dark mode
    primary: light blue
  - scheme: slate
    media: "(prefers-color-scheme: dark)"
    toggle:
      icon: material/brightness-4
      name: Switch to light mode
    primary: light blue
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.sections
    - navigation.indexes
    - toc.follow
    - navigation.top
extra:
  homepage: https://docs.illenium.dev
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/iLLeniumStudios
    - icon: fontawesome/brands/discord 
      link: https://discord.illenium.dev
  generator: false
plugins:
  - search
  - awesome-pages
  - mkdocs-video

copyright: Copyright &copy; 2023 iLLeniumStudios
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - tables
extra_css:
  - stylesheets/extra.css
